### PR TITLE
Add incompatible version

### PR DESCRIPTION
**Pull request by MmtBkn**
My app is crashing (RJ-3050Ai). Any luck fixing this @VictorCoding @gordol ?  Here is report;

```
Last Exception Backtrace:
0   CoreFoundation                	0x18572f164 __exceptionPreprocess + 124
1   libobjc.A.dylib               	0x184978528 objc_exception_throw + 55
2   CoreFoundation                	0x18572f0ac +[NSException raise:format:] + 115
3   CoreFoundation                	0x1856c5ae8 mutateError + 203
4   hello                         	0x10286cf08 -[BRPtouchPrinter setPrinterName:] + 413448 (BRPtouchPrinter.mm:520)
5   hello                         	0x10286cc54 -[BRPtouchPrinter initWithPrinterName:] + 412756 (BRPtouchPrinter.mm:420)
6   hello                         	0x10286cc88 -[BRPtouchPrinter initWithPrinterName:interface:] + 412808 (BRPtouchPrinter.mm:429)
7   hello                         	0x102843768 -[BrotherPrinter printViaSDK:] + 243560 (BrotherPrinter.m:455)
```

```
Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001852442e8 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x000000018535d748 pthread_kill$VARIANT$armv81 + 360
2   libsystem_c.dylib             	0x00000001851b2fbc abort + 140
3   libc++abi.dylib               	0x0000000184950068 __cxa_bad_cast + 0
4   libc++abi.dylib               	0x0000000184950210 default_unexpected_handler+ 8720 () + 0
5   libobjc.A.dylib               	0x0000000184978810 _objc_terminate+ 34832 () + 124
6   libc++abi.dylib               	0x000000018496854c std::__terminate(void (*)+ 107852 ()) + 16
7   libc++abi.dylib               	0x0000000184967ea8 __cxxabiv1::exception_cleanup_func+ 106152 (_Unwind_Reason_Code, _Unwind_Exception*) + 0
8   libobjc.A.dylib               	0x000000018497865c _objc_exception_destructor+ 34396 (void*) + 0
9   CoreFoundation                	0x000000018572f0ac -[NSException initWithCoder:] + 0
10  CoreFoundation                	0x00000001856c5ae8 mutateError + 204
11  hello                         	0x000000010286cf08 -[BRPtouchPrinter setPrinterName:] + 413448 (BRPtouchPrinter.mm:523)
12  hello                         	0x000000010286cc54 -[BRPtouchPrinter initWithPrinterName:] + 412756 (BRPtouchPrinter.mm:420)
13  hello                         	0x000000010286cc88 -[BRPtouchPrinter initWithPrinterName:interface:] + 412808 (BRPtouchPrinter.mm:429)
14  hello                         	0x0000000102843768 -[BrotherPrinter printViaSDK:] + 243560 (BrotherPrinter.m:455)
```

### CODE REVIEW

**Comment by gordol** [comment]
That stack trace isn't very helpful. What are you doing when this happens?

**Comment by MmtBkn** [comment]
Unfortunately, it's failing without error. This is from system crash log. Is there way to catch it? 

I get it when I call printViaSDK. It's able to find devices, and when I call setPrinter it returns success too.

**Comment by gordol** [comment]
Do you also have a problem with any other printer versions?

**Comment by gordol** [comment]
Also what version of IOS are you using? Can you share any code to reproduce the issue?

**Comment by MmtBkn** [comment]
I don't have any other printer.

Here is repo for code; https://github.com/MmtBkn/RJ3050AI-cordova

When I click button, It's connecting and setting printer (both calling success callback and I'm able to see device) but when I call printViaSDK, app is crashing, I think not even connecting the printer..

iOS version is 11.2.6

**Comment by gordol** [comment]
I don't have iOS 11 on my iPad, but I'll try to load this up soon and see if I can reproduce. For what it's worth, I haven't really even tested the iOS version of this plugin... I only built the Android version initially, and others extended it to work with iOS. That's why the iOS branch is not merged into master yet on my repo. I'm travelling tomorrow, but I should be able to try this out in a week or so. Sorry for the delay.

**Comment by gordol** [comment]
Have you checked here, btw?

https://github.com/gordol/cordova-brother-label-printer/pull/11

**Comment by gordol** [comment]
There's also another pull request here: https://github.com/gordol/cordova-brother-label-printer/pull/10

**Comment by MmtBkn** [comment]
Closing this PR since It's been stale for over a year.

**Pull request closed without merging**
